production:
  solr:
    hostname: localhost
    #port: 8080
    port: 8983
    path: '/solr'
    log_level: WARNING
    # read_timeout: 2
    # open_timeout: 0.5
  auto_commit_after_request: false
development:
  solr:
    hostname: localhost
    #port: 8080
    #port: 8982
    port: 8983
    path: '/solr'
    log_level: INFO
  auto_commit_after_request: false
test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
