module CategoriesHelper

def get_category_icon(category)
    if !category.nil?
    case category.id
    when 1
      return "markers/lodging_0star.png"
    when 2
      return "markers/mall.png"
    when 3
      return "markers/landmark.png"
    when 4
      return "markers/restaurant.png"
    when 5
      return "markers/jogging.png"
    when 6
      return "markers/pinother.png"
    when 7
      return "markers/apartment-3.png"
    when 8
      return "markers/bed_breakfast1-2.png"
    when 9
      return "markers/condominium.png"
    when 10
      return "markers/hotel_0star.png"
    when 11
      return "markers/motel-2.png"
    when 12
      return "markers/resort.png"
    when 13
      return "markers/villa.png"
    when 14
      return "markers/youthhostel.png"
    when 15
      return "markers/apple.png"
    when 16
      return "markers/butcher-2.png"
    when 17
      return "markers/candy.png"
    when 18
      return "markers/conveniencestore.png"
    when 19
      return "markers/departmentstore.png"
    when 20
      return "markers/drugstore.png"
    when 21
      return "markers/computers.png"
    when 22
      return "markers/fishingstore.png"
    when 23
      return "markers/fruits.png"
    when 24
      return "markers/grocery.png"
    when 25
      return "markers/mall.png"
    when 26
      return "markers/market.png"
    when 27
      return "markers/music.png"
    when 28
      return "markers/glasses.png"
    when 29
      return "markers/pets.png"
    when 30
      return "markers/supermarket.png"
    when 31
      return "markers/toys.png"
    when 32
      return "markers/arch.png"
    when 33
      return "markers/birds-2.png"
    when 34
      return "markers/bridge_modern.png"
    when 35
      return "markers/castle-2.png"
    when 36
      return "markers/cathedral.png"
    when 37
      return "markers/cinema.png"
    when 38
      return "markers/citysquare.png"
    when 39
      return "markers/citywalls.png"
    when 40
      return "markers/comedyclub.png"
    when 41
      return "markers/dancinghall.png"
    when 42
      return "markers/fountain-2.png"
    when 43
      return "markers/videogames.png"
    when 44
      return "markers/hotspring.png"
    when 45
      return "markers/information.png"
    when 46
      return "markers/jacuzzi.png"
    when 47
      return "markers/jazzclub.png"
    when 48
      return "markers/lighthouse-2.png"
    when 49
      return "markers/marina-2.png"
    when 50
      return "markers/memorial.png"
    when 51
      return "markers/monument.png"
    when 52
      return "markers/museum_archeological.png"
    when 53
      return "markers/artgallery.png"
    when 54
      return "markers/museum_science.png"
    when 55
      return "markers/music_live.png"
    when 56
      return "markers/olympicsite.png"
    when 57
      return "markers/palace-2.png"
    when 58
      return "markers/planetarium-2.png"
    when 59
      return "markers/ruins-2.png"
    when 60
      return "markers/statue-2.png"
    when 61
      return "markers/summercamp.png"
    when 62
      return "markers/theater.png"
    when 63
      return "markers/tower.png"
    when 64
      return "markers/u-pick_stand.png"
    when 65
      return "markers/vineyard-2.png"
    when 66
      return "markers/windmill-2.png"
    when 67
      return "markers/worldheritagesite.png"
    when 68
      return "markers/zoo.png"
    when 69
      return "markers/bread.png"
    when 70
      return "markers/bar.png"
    when 71
      return "markers/beergarden.png"
    when 72
      return "markers/cafetaria.png"
    when 73
      return "markers/coffee.png"
    when 74
      return "markers/fastfood.png"
    when 75
      return "markers/fishchips.png"
    when 76
      return "markers/foodtruck.png"
    when 77
      return "markers/icecream.png"
    when 78
      return "markers/kebab.png"
    when 79
      return "markers/patisserie.png"
    when 80
      return "markers/pizzaria.png"
    when 81
      return "markers/restaurant.png"
    when 82
      return "markers/restaurant_african.png"
    when 83
      return "markers/restaurant_breakfast.png"
    when 84
      return "markers/restaurant_buffet.png"
    when 85
      return "markers/restaurant_chinese.png"
    when 86
      return "markers/restaurant_greek.png"
    when 87
      return "markers/restaurant_indian.png"
    when 88
      return "markers/restaurant_italian.png"
    when 89
      return "markers/japanese-food.png"
    when 90
      return "markers/restaurant_korean.png"
    when 91
      return "markers/restaurant_mediterranean.png"
    when 92
      return "markers/restaurant_mexican.png"
    when 93
      return "markers/restaurant_steakhouse.png"
    when 94
      return "markers/restaurant_tapas.png"
    when 95
      return "markers/restaurant_thai.png"
    when 96
      return "markers/restaurant_turkish.png"
    when 97
      return "markers/restaurant_vegetarian.png"
    when 98
      return "markers/takeaway.png"
    when 99
      return "markers/teahouse.png"
    when 100
      return "markers/winebar.png"
    when 101
      return "markers/baseball.png"
    when 102
      return "markers/basketball.png"
    when 103
      return "markers/billiard-2.png"
    when 104
      return "markers/cricket.png"
    when 105
      return "markers/fishing.png"
    when 106
      return "markers/fitness.png"
    when 107
      return "markers/golfing.png"
    when 108
      return "markers/horseriding.png"
    when 109
      return "markers/icehockey.png"
    when 110
      return "markers/iceskating.png"
    when 111
      return "markers/kayak1.png"
    when 112
      return "markers/karate.png"
    when 113
      return "markers/skiing.png"
    when 114
      return "markers/soccer.png"
    when 115
      return "markers/swimming.png"
    when 116
      return "markers/tennis.png"
    when 117
      return "markers/volleyball.png"
    when 118
      return "markers/climbing.png"
    when 119
      return "markers/waterskiing.png"
    when 120
      return "markers/airport.png"
    when 121
      return "markers/barber.png"
    when 122
      return "markers/beautysalon.png"
    when 123
      return "markers/bouddha.png"
    when 124
      return "markers/busstop.png"
    when 125
      return "markers/cablecar.png"
    when 126
      return "markers/carrental.png"
    when 127
      return "markers/carwash.png"
    when 128
      return "markers/cemetary.png"
    when 129
      return "markers/chapel-2.png"
    when 130
      return "markers/church-2.png"
    when 131
      return "markers/congress.png"
    when 132
      return "markers/cruiseship.png"
    when 133
      return "markers/daycare.png"
    when 134
      return "markers/fillingstation.png"
    when 135
      return "markers/firemen.png"
    when 136
      return "markers/funicolar-22x22.png"
    when 137
      return "markers/workshop.png"
    when 138
      return "markers/harbor.png"
    when 139
      return "markers/highschool.png"
    when 140
      return "markers/library.png"
    when 141
      return "markers/mosquee.png"
    when 142
      return "markers/nailsalon.png"
    when 143
      return "markers/pagoda-2.png"
    when 144
      return "markers/parkinggarage.png"
    when 145
      return "markers/playground.png"
    when 146
      return "markers/police.png"
    when 147
      return "markers/postal.png"
    when 148
      return "markers/school.png"
    when 149
      return "markers/templehindu.png"
    when 150
      return "markers/toilets.png"
    when 151
      return "markers/train.png"
    when 152
      return "markers/tramway.png"
    when 153
      return "markers/travel_agency.png"
    when 154
      return "markers/underground.png"
    when 155
      return "markers/university.png"
    when 156
      return "markers/medicine.png"
    when 157
      return "markers/chiropractor.png"
    when 158
      return "markers/dentist.png"
    when 159
      return "markers/medicine.png"
    when 160
      return "markers/hospital-building.png"
    when 161
      return "markers/massage.png"
    when 162
      return "markers/medicalstore.png"
    when 163
      return "markers/ophthalmologist.png"
    when 164
      return "markers/sauna.png"
    when 165
      return "markers/spa.png"
    when 166
      return "markers/veterinary.png"
    when 167
      return "markers/yoga.png"
    when 168
      return "markers/aircraftsmall.png"
    when 169
      return "markers/aquarium.png"
    when 170
      return "markers/atv.png"
    when 171
      return "markers/bank.png"
    when 172
      return "markers/motorcycle.png"
    when 173
      return "markers/bowling.png"
    when 174
      return "markers/car.png"
    when 175
      return "markers/casino-2.png"
    when 176
      return "markers/circus.png"
    when 177
      return "markers/outlet2.png"
    when 178
      return "markers/dinopark.png"
    when 179
      return "markers/karting.png"
    when 180
      return "markers/phones.png"
    when 181
      return "markers/jewelry.png"
    when 182
      return "markers/magicshow.png"
    when 183
      return "markers/paintball.png"
    when 184
      return "markers/perfumery.png"
    when 185
      return "markers/restaurant_fish.png"
    when 186
      return "markers/tailor.png"
    when 187
      return "markers/shoes.png"
    when 188
      return "markers/schreibwaren_web.png"
    when 189
      return "markers/textiles.png"
    when 190
      return "markers/themepark.png"
    when 191
      return "markers/waterpark.png"
    when 192
      return "markers/2hand.png"
    when 193
      return "markers/atm-2.png"
    when 194
      return "markers/bicycle_shop.png"
    when 195
      return "markers/brewery1.png"
    when 196
      return "markers/camping-2.png"
    when 197
      return "markers/christmasmarket.png"
    when 198
      return "markers/court.png"
    when 199
      return "markers/currencyexchange.png"
    when 200
      return "markers/customs.png"
    when 201
      return "markers/bike_rising.png"
    when 202
      return "markers/embassy.png"
    when 203
      return "markers/gifts.png"
    when 204
      return "markers/gondola-2.png"
    when 205
      return "markers/hookah_final.png"
    when 206
      return "markers/laboratory.png"
    when 207
      return "markers/laundromat.png"
    when 208
      return "markers/radio-station-2.png"
    when 209
      return "markers/radio-station-2.png"
    when 210
      return "markers/atm-2.png"
    when 211
      return "markers/leaf.png"
    when 212
      return "markers/mall.png"
    when 213
      return "markers/townhouse.png"
    when 214
      return "markers/office-building.png"
    when 215
      return "markers/badminton-2.png"
    when 216
      return "markers/beach.png"
    when 217
      return "markers/canyon-2.png"
    when 218
      return "markers/cave-2.png"
    when 219
      return "markers/conference.png"
    when 220
      return "markers/dam.png"
    when 221
      return "markers/diving.png"
    when 222
      return "markers/ferriswheel.png"
    when 223
      return "markers/festival.png"
    when 224
      return "markers/forest2.png"
    when 225
      return "markers/geyser-2.png"
    when 226
      return "markers/glacier-2.png"
    when 227
      return "markers/hiking.png"
    when 228
      return "markers/historicalquarter.png"
    when 229
      return "markers/jazzclub.png"
    when 230
      return "markers/kiosk.png"
    when 231
      return "markers/lake.png"
    when 232
      return "markers/stripclub2.png"
    when 233
      return "markers/monument-historique-icon-white-22x22.png"
    when 234
      return "markers/mountains.png"
    when 235
      return "markers/movierental.png"
    when 236
      return "markers/observatory.png"
    when 237
      return "markers/pyramid.png"
    when 238
      return "markers/scubadiving.png"
    when 239
      return "markers/shipwreck.png"
    when 240
      return "markers/sledge.png"
    when 241
      return "markers/snorkeling.png"
    when 242
      return "markers/stadium.png"
    when 243
      return "markers/volcano-2.png"
    when 244
      return "markers/waterfall-2.png"
    when 245
      return "markers/historicalquarter.png"
    when 246
      return "markers/office-building.png"
    when 247
      return "markers/citywalls.png"
    when 248
      return "markers/forest.png"
    when 249
      return "markers/milk_and_cookies.png"
    else
      return "markers/pinother.png"
    end
    end
  end
  
end
